<div class="container">
<h1 style="margin-right:0cm;margin-left:0cm;font-size:32px;font-family:SimSun;font-weight:bold;margin-top:12.0pt;margin-bottom:6.0pt;background:white;"><span style='font-size:29px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Privacy Policy</span></h1>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>The Personal Data Protection Notice (&ldquo;the Notice&rdquo;) is issued pursuant to the enactment of the Personal Data Protection Act 2010 (&ldquo;the Act&rdquo;) to regulate the collection and processing of your Personal Data (as herein defined) by ePink Health &nbsp;HEALTH SDN.BHD.., its subsidiaries, associates, jointly controlled entities, affiliates (&ldquo;ePink Health &rdquo;).</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We, ePink Health &nbsp;value the trust You place in Us. That is why We insist upon the highest standards for secure transactions and customer information privacy. Please read the following statement to learn about Our information gathering and dissemination practices. Our privacy policy is subject to change at any time without notice. To make sure You are aware of any changes, please review this policy periodically.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>By visiting this Website or downloading this App you agree to be bound by the terms and conditions of this Privacy Policy. If You do not agree please do not use or access our Website/App. By mere use of the Website/App, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Service.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>If you have any questions or concerns regarding this Privacy Policy, you should contact our Customer Support Desk at&nbsp;</span><span style='font-family:"Calibri Light",sans-serif;'>hello@epink.health</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;</span></strong><strong><span style='font-size:21px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>SCOPE OF POLICY</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>This policy applies to e-pink.health (hereinafter known as the Website) and the mobile application ePink Health &nbsp;(hereinafter referred to as the App). It regulates the processing of information relating to You and grants You various rights in respect of Your personal data.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;DEFINITIONS</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&lsquo;We&rsquo;/ &lsquo;Our&rsquo;/ &lsquo;Us&rsquo; shall mean and refer to ePink Health .</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&lsquo;You&rsquo;/ &lsquo;Your&rsquo;/ &lsquo;Yourself&rsquo;/ &lsquo;User&rsquo; shall mean and refer to natural and legal entities that enter and/or use the Website/App, either to put up content or to view/use such content that has been put up. &lsquo;Personal Information&rsquo; shall mean and refer to any personally identifiable information that We may collect from You as more particualrly provided for below. &lsquo;Third Parties&rsquo; refer to any application, website, company or individual apart from the User and the owner of the Website/App.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>INFORMATION COLLECTED</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>You have to register with Your personal information/ information to enjoy the services offered by Our Website and/or App. We may collect the following general types of information about You when You visit Our Site: personal information, demographic information, behavioural information, and indirect information.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Personal Information means any information that may be used to identify an individual. This includes but is not limited to Name, Gender, Mailing Address, Photo, Telephone Number, Email ID, marital status, information of spouse / children, occupation, profession, designation, income range, credit card details, bank account number, information of employer, race, nationality and any other information that can be used to identify You. We also collect body vitals including but not limited to height weight, age, food habits, BMI index, fat percentage, allergies, symptoms, physical and mental or other health conditions or medical records, history and other relevant health traits.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We may occasionally ask You to complete optional online surveys. These surveys may ask You for contact information and demographic information (like postcode, age, or income level). We use this data to tailor Your experience at our Website/App, providing You with content that we think You might be interested in and to display content according to Your preferences.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Indirect information may be collected by Us about You when You use certain third party services on Our Site and the collection of such information is considered necessary for that purpose. We also use analytic to track You in remarketing.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>USE OF INFORMATION</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We use the information We gather on the Site for the following purposes:</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;Individual User information.</span></p>
<ol start="1" style="margin-bottom:0cm;" type="1">
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To provide Our services. This includes providing communications, promotions and information on events which may be of interest to You that is organised, managed, facilitated, provided sponsored and/or participated by ePink Health .</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To communicate with you.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To provide you with information about the activities, products, services, events and programs offered by third parties that may interest you.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To facilitate payment in connection with the business or contractual dealings between ePink Health &nbsp;and you and/or your company.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To respond to any queries You may have and to communicate information to You. These include sending You e-mail or other communications regarding updates at the Website/App to contact You about Your opinion of current products and/or services or potential new products and/or services that may be offered.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To conduct research, analysis, study, assessment, survey and or prepare reports or statistics to operate and improve ePink Health &rsquo;s business activities and/or the Website/App in order to foster a positive user experience.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To comply with the applicable laws.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>To investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Our Terms of Service, or as otherwise required by law.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>At the time of registration, You have to fill in Your Personal Information in order to obtain an account, which can be used subsequently to log into the App.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>For any other purpose(s) as ePink Health &nbsp;shall deem fit and proper.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;Information about all visitors collectively</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We gather information about all of Our Users collectively, such as what areas users visit most frequently and what services users access the most. Such data is used anonymously and in the aggregate. This information helps Us determine what is most beneficial for Our Users, and how We can continually create a better overall experience for them.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>DISCLOSURE OF THE INFORMATION</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We disclose the information to the third parties in the method specified below, including, but not limited to:</span></p>
<ol start="1" style="margin-bottom:0cm;" type="1">
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Disclosing the content posted by You on the Website/App, in order that our medical / healthcare / pharmacy practitioners, professionals and service providers who provide various services whom we have contractual arrangements with may facilitates our business operations.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Sharing Your information with third parties who help Us in the delivery of our own services to you. Information is disclosed to companies and individuals who are authorised by Us to perform functions on Our behalf.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Disclosing such information to third parties if You consent to such disclosure. If You indicate that You would like to receive information about the opportunities, products or services of third parties, We supply Your contact information to select third parties such organisers of or any entity associated with the events, or others for the purpose of sending You e-mail or otherwise communicating with You.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We may share this information with Our partners and affiliates, but only in the aggregate, so that they too may understand how visitors use Our Website/App, and also create a better overall experience for You. We also share aggregated anonymous information about visitors to the Website/App with Our clients, partners, other website visitors, and other third parties so that they can understand the kinds of visitors and how they use the website in order to serve advertisements and other kinds of marketing information to You on Our Website/App.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We may disclose and transfer such information to a third party who acquires Our business units, whether such acquisition is by way of merger, consolidation or purchase of all or a substantial portion of Our assets. You will be notified of the sale of all or a substantial portion of Our business to a third party by email or through a prominent notice posted on the Website/App.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We disclose information if legally required to, pursuant to an order from a governmental entity, local authorities, statutory authorities, enforcement agencies under the law and industry regulatory or other authorities or in good faith. We will disclose the information to:</span></li>
</ol>
<ol start="6" style="margin-bottom:0cm;" type="1">
    <ol start="1" style="margin-bottom:0cm;" type="1">
        <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>conform to legal requirements or comply with legal process;</span></li>
        <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>protect our rights or property or our affiliated companies;</span></li>
        <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>prevent a crime or protect national security; or</span></li>
        <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>protect the personal safety of users or the public.</span></li>
    </ol>
</ol>
<ol start="7" style="margin-bottom:0cm;" type="1">
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>In case of medical emergency, if any person intends to threaten to commit suicide or is in a state of medical emergency, the company holds the right to disclose the identity of the patient to the relevant sources.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>ePink Health &rsquo;s employees, auditors, consultants, accountants, lawyers, real estate agents, vendors, co-marketing partner, insurance company, property development and management manager and professional advisers.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>If you are subscribing to ePink Health &nbsp;services via your employer directly or indirectly through Insurer or Third Party Administrator (TPA) provider, we are obligated to share your medical information with your Insurer, TPA and/or employer for the purpose of billing and claims. THIS DOES NOT APPLY TO INDIVIDUAL SELF-PAYING PATIENT using e-pink.health</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>EXTERNAL LINKS ON THE APP/WEBSITE</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>The Website/App may include advertisements hyperlinks to other websites, applications, content or resources. We have no control over such external links present in the App/Website, which are provided by persons or companies other than Us. You acknowledge and agree that We are not responsible for any collection or disclosure of Your Personal Information by any external sites, applications, companies or persons, nor are do We endorse any advertising, products or other material on or available from such external application, websites or resources.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>You further acknowledge and agree that We are not liable for any loss or damage which may be incurred by You as a result of the collection and/or disclosure of Your personal information by external applications, sites or resources, or as a result of any reliance placed by You on the completeness, accuracy or existence of any advertising, products or other materials on, or available from such applications, websites or resources. These external applications, websites and resource providers may have their own privacy policies governing the collection, storage, retention and disclosure of Your Personal Information that You may be subject to. We recommend that You enter the external application or website and review their privacy policy. We allow third parties/individuals to display advertisements when you use the Website/App.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>SECURITY PRECAUTIONS</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Our Website/App has stringent security measures in place to protect the loss, misuse, and alteration of the information under Our control. Whenever You change or access is in Our possession We adhere to strict security guidelines, protecting it against unauthorized access.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>A &quot;Force Majeure Event&quot; shall mean any event that is beyond the reasonable control and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, unauthorised access to computer data and storage device, computer crashes, breach of security and encryption, etc.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>CHOICE/OPT-OUT</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We provide all Users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of Our partners, and from us in general, after setting up an account.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>CONFIDENTIALITY</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We do not collect sensitive personal data or information of Users like password of Your email account, password of Your account on the Website/App, biometric information such as finger prints, voice &amp; facial patterns and DNA any other sensitive information which is confidential or sensitive by its nature, without your explicit consent or unless necessary by law. Financial information such as Bank Account details or Credit Card or Debit Card or other payment related details are collected at the payment gateway by the payment facilitator.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;UPDATE AND REMOVE INFORMATION/ACCOUNT</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>You may have access to, review, correct, update, change or delete your account profile information at any time. Simply log into your account, go to your profile, and make the necessary changes.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Before providing you with a copy of your personal information or correcting, updating or deleting such information, We reserve the right to verify and authenticate Your identity and the personal information to which You have requested access. Access to or correction, updating or deletion of Your personal information may be denied or limited by Us if it would violate another person&rsquo;s rights and/or as otherwise permitted by applicable law.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>CHANGES TO THIS PRIVACY POLICY</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>We reserve the right to update, change or modify this Policy at any time. The Policy shall come to effect from the date of such update, change or modification. If You continue to use Your account and/or access the Website/App even after any such changes have been made, it would be deemed to be an implied consent to the changed policy.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>COOKIES AND OTHER TRACKING TECHNOLOGIES</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Our Website/App and some of our Web pages utilize &lsquo;cookies&rsquo; and other tracking technologies. A &quot;cookie&quot; is a small text file that may be used, for example, to collect information about Site activity. Some cookies and other technologies may serve to recall Personal Information previously indicated by a Web user. Most browsers allow You to control cookies, including whether or not to accept them and how to remove them.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>You may set most browsers to notify You if You receive a cookie, or You may choose to block cookies with Your browser, but please note that if You choose to erase or block Your cookies, You will need to re-enter Your original user ID and password to gain access to certain parts of the Website/App.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Tracking technologies may record information such as Internet domain and host names; Internet protocol (IP) addresses; browser software and operating system types; stream patterns; and dates and times that Our App is accessed. Our use of cookies and other tracking technologies allows Us to improve Our Website/App and Your experience. We may also analyze information that does not contain Personal Information for trends and statistics.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>DATA TRANSFER AND SHARING</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Where ePink Health &nbsp;consider it is necessary or appropriate for the purposes of data storage or processing or providing any service or product on our behalf to you, ePink Health &nbsp;may transfer the Personal Information to ePink Health &rsquo;s group of companies or any third party service or product providers within or outside the country in which ePink Health &rsquo;s group of companies are established under similar conditions, confidentiality and level of security safeguards.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;INDEMNITY</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>You agree and undertake to indemnify Us against any suit or dispute by any Third Party arising out of disclosure of Personal Information by You to Third Parties either through Our Website/App or otherwise and Your use and access of websites, applications and resources of Third Parties. We assume no liability for any actions of Third Parties with regard to Your Personal Information, which You may have disclosed to such Third Parties.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br>&nbsp;SEVERABILITY</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Each paragraph of this Privacy Policy shall be and remain separate from and independent of and severable from all and any other paragraphs herein except where otherwise expressly indicated or indicated by the context of the agreement.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>The decision or declaration that one or more of the paragraphs are null and void shall have no effect on the remaining paragraphs of this privacy policy.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>CONTACT INFORMATION</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Any feedback or comments about this Privacy Policy is welcome and can be sent at hello@epink.health We will employ all commercially reasonable efforts to address the same.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'><br> <strong>CONFLICT</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>In the event of any inconsistency between the English version and the Bahasa Malaysia version of the Notice, the English version shall prevail over the Bahasa Malaysia version.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Notis Perlindungan Data Peribadi (&quot;Notis&quot;) dikeluarkan menurut Akta Undang-undang Perlindungan Data Peribadi 2010 (&quot;Akta&quot;) untuk mengawal selia pengumpulan dan pemprosesan Data Peribadi anda (seperti yang dinyatakan di sini) oleh &nbsp;ePink Health &nbsp; HEALTH SDN.BHD.., anak syarikatnya, syarikat bersekutu, entiti kawalan bersama, sekutu-sekutunya (&quot;ePink Health &quot;).</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami, ePink Health &nbsp;sangat menghargai kepercayaan yang anda berikan kepada kami. Oleh itu, kami meletakkan penanda aras yang tertinggi untuk diberikan kepada anda supaya setiap urusan transaksi dan privasi maklumat pelanggan adalah selamat. Sila baca kenyataan-kenyataan berikut untuk mengetahui tentang amalan-amalan pengumpulan dan penyebaran maklumat kami. Dasar privasi kami boleh berubah pada bila-bila masa sahaja tanpa sebarang notis. Untuk memastikan Anda menyedari sebarang perubahan yang berlaku, sila semak dasar ini secara berkala.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Dengan melawat Laman sesawang ini atau memuat turun Aplikasi ini, anda telah bersetuju untuk terikat dengan terma-terma dan syarat-syarat Dasar Privasi ini. Sekiranya Anda tidak bersetuju, sila berhenti daripada menggunakan atau mengakses laman sesawang / Aplikasi kami. Dengan perbuatan meneruskan penggunaan laman sesawang / Aplikasi ini , anda dengan secara jelas telah bersetuju dengan penggunaan dan pendedahan maklumat peribadi anda mengikut Dasar Privasi ini. Dasar Privasi ini termasuk di dalam dan tertakluk kepada Syarat-syarat Perkhidmatan.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Jika anda mempunyai sebarang pertanyaan atau kebimbangan berhubung dengan Dasar Privasi ini, anda boleh menghubungi bahagian Perkhidmatan Pelanggan kami di<strong>&nbsp; hello@epink.health</strong></span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>SKOP POLISI</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Polisi ini digunapakai oleh e-pink.health (selepas ini akan dirujuk sebagai laman sesawang) dan aplikasi mudah alih ePink Health &nbsp;(selepas ini akan dirujuk sebagai Aplikasi). Polisi ini akan mengawal selia sebarang urusan pemprosesan maklumat yang berkaitan dengan Anda dan memberikan pelbagai hak yang berkaitan dengan data peribadi Anda.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>DEFINISI</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&apos;Kami / &lsquo;kita&apos; bermaksud dan merujuk kepada ePink Health .</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&apos;Anda&apos;/&apos;Pengguna&apos; akan memberikan maksud dan merujuk kepada entiti semulajadi dan entiti undang-undang yang memasuki dan / atau menggunakan laman sesawang / Aplikasi, sama ada untuk menyiapkan kandungan atau untuk melihat / menggunakan kandungan-kandungan sedemikian yang telah disediakan. &apos;Maklumat Peribadi&apos; bermaksud dan merujuk kepada apa-apa maklumat yang boleh dikenalpasti sebagai peribadi yang boleh Kami perolehi daripada Anda sebagaimana yang akan diperuntukkan dengan lebih terperinci di bawah. &apos;Pihak Ketiga&apos; merujuk kepada sebarang aplikasi, laman sesawang, syarikat atau individu selain Pengguna dan pemilik laman sesawang / Aplikasi.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>MAKLUMAT YANG DIKUMPULKAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Anda perlu mendaftarkan Maklumat / maklumat peribadi anda untuk menikmati perkhidmatan yang ditawarkan oleh laman sesawang dan / atau Aplikasi kami. Kami mungkin akan mengumpulkan beberapa jenis maklumat-maklumat umum mengenai Anda ketika Anda melawat laman sesawang kami seperti: maklumat peribadi, maklumat demografi, maklumat tingkah laku, dan maklumat-maklumat yang diminta secara tidak langsung.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Maklumat Peribadi bermaksud apa-apa maklumat yang boleh digunakan untuk mengenal pasti individu. Ini termasuk tetapi tidak terhad kepada, Nama, Jantina, Alamat menyurat, Foto, Nombor Telefon, ID E-mel, status perkahwinan, maklumat pasangan / anak, pekerjaan, profesion, jawatan, julat pendapatan, butiran kad kredit, nombor akaun bank, majikan, bangsa, kewarganegaraan dan apa-apa maklumat lain yang boleh digunakan untuk mengenal pasti Anda. Kami juga mengumpul maklumat penting pada badan termasuk tetapi tidak terhad kepada ketinggian, berat badan, umur, tabiat makanan, indeks BMI, peratusan lemak, alergi, gejala, keadaan fizikal dan mental atau keadaan kesihatan yang lain atau rekod perubatan, sejarah dan lain-lain ciri kesihatan yang berkaitan.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami boleh meminta Anda untuk melengkapkan kaji selidik pilihan dalam talian. Kaji selidik ini boleh meminta maklumat hubungan dan maklumat demografi anda (seperti poskod, umur, atau tahap pendapatan). Kami menggunakan data ini untuk menyesuaikan Pengalaman anda di laman sesawang / Aplikasi kami, menyediakan Anda dengan kandungan yang kami fikir Anda mungkin berminat dan memaparkan kandungan mengikut keutamaan anda.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Maklumat tidak langsung boleh dikumpulkan oleh Kami tentang Anda apabila Anda menggunakan perkhidmatan pihak ketiga tertentu di Laman sesawang Kami dan pengumpulan maklumat tersebut dianggap perlu untuk tujuan tersebut. Kami juga menggunakan analytic untuk mengesan Anda dalam pemasaran semula.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PENGGUNAAN MAKLUMAT</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami menggunakan maklumat yang Kami kumpulkan di dalam Laman ini untuk tujuan berikut:</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Maklumat Pengguna individu.</span></p>
<ul style="margin-bottom:0cm;" type="disc">
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk menyediakan perkhidmatan kami. Ini termasuk komunikasi, promosi dan maklumat mengenai acara yang mungkin menarik bagi Anda yang dianjurkan, diurus, dimudahcarakan, disediakan, ditaja dan / atau disertai oleh ePink Health .</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk berkomunikasi dengan anda.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk memberi anda maklumat mengenai aktiviti, produk, perkhidmatan, acara dan program yang ditawarkan oleh pihak ketiga yang mungkin menarik minat anda.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk memudahkan pembayaran berkaitan dengan urusan perniagaan atau kontrak antara ePink Health &nbsp;dan anda, dan / atau syarikat anda.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk menjawab sebarang pertanyaan yang Anda ada dan untuk menyampaikan maklumat kepada Anda. Ini termasuk menghantar e-mel atau komunikasi lain mengenai kemas kini di laman sesawang / Aplikasi untuk menghubungi Anda mengenai pendapat anda tentang produk dan / atau perkhidmatan semasa atau produk baru dan / atau perkhidmatan baru yang mungkin ditawarkan.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk menjalankan penyelidikan, analisis, kajian, penilaian, tinjauan dan atau menyediakan laporan atau statistik untuk mengendalikan dan meningkatkan aktiviti perniagaan ePink Health &nbsp;dan / atau laman sesawang / Aplikasi untuk memupuk pengalaman pengguna yang positif.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk mematuhi undang-undang yang berkenaan.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk menyiasat, menghalang, atau mengambil tindakan berhubung aktiviti haram, penipuan yang disyaki, situasi yang melibatkan ancaman yang berpotensi terhadap keselamatan fizikal seseorang, pelanggaran Syarat Perkhidmatan kami, atau sebagaimana yang dikehendaki oleh undang-undang.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Pada masa pendaftaran, Anda perlu mengisi Maklumat Peribadi Anda untuk mendapatkan akaun, yang boleh digunakan kemudiannya untuk log masuk ke dalam aplikasi.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Untuk apa-apa tujuan lain yang dianggap sesuai oleh ePink Health .</span></li>
</ul>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Maklumat mengenai semua pelawat secara kolektif</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami mengumpul maklumat mengenai semua Pengguna kami secara kolektif, seperti kawasan yang sering dikunjungi oleh pengguna dan perkhidmatan pengguna yang paling banyak diakses. Data sedemikian digunakan secara tidak dikenalpasti dan dalam agregat. Maklumat ini membantu Kami menentukan perkara yang paling bermanfaat bagi Pengguna Kami, dan membantu Kami untuk terus mencipta pengalaman keseluruhan yang lebih baik untuk mereka.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PENDEDAHAN MAKLUMAT</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami mendedahkan maklumat tersebut kepada pihak ketiga dalam kaedah yang dinyatakan di bawah, termasuk, tetapi tidak terhad kepada:</span></p>
<ul style="margin-bottom:0cm;" type="disc">
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Mengisytiharkan kandungan yang diposkan oleh Anda di laman sesawang / Aplikasi, agar pengamal perubatan / penjagaan kesihatan / farmasi, profesional dan penyedia perkhidmatan kami dapat menyediakan pelbagai perkhidmatan yang kami ada dengan perjanjian kontrak bagi memudahkan operasi perniagaan kami.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Berkongsi maklumat anda dengan pihak ketiga yang membantu Kami dalam penyampaian perkhidmatan kami sendiri kepada anda. Maklumat didedahkan kepada syarikat dan individu yang diberi kuasa oleh Kami untuk melaksanakan fungsi bagi pihak kami.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Pendedahan maklumat tersebut kepada pihak ketiga jika Anda bersetuju dengan pendedahan tersebut. Jika Anda menyatakan bahawa Anda ingin menerima maklumat mengenai peluang, produk atau perkhidmatan pihak ketiga, Kami akan membekalkan maklumat anda untuk memilih pihak ketiga penganjur atau mana-mana entiti yang berkaitan dengan acara tersebut, atau orang lain untuk tujuan menghantar kepada Anda e-mel atau sebaliknya berkomunikasi dengan Anda.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami mungkin berkongsi maklumat ini dengan rakan kongsi dan sekutu kami, tetapi hanya dalam agregat, supaya mereka juga dapat memahami bagaimana pelawat menggunakan laman sesawang / Aplikasi kami, dan juga membuat pengalaman keseluruhan yang lebih baik untuk Anda. Kami juga berkongsi maklumat-maklumat peribadi yang dikumpul tentang pelawat ke laman sesawang / Aplikasi dengan Pelanggan, rakan kongsi, pelawat laman sesawang yang lain, dan pihak ketiga yang lain supaya mereka dapat memahami jenis pelawat dan bagaimana mereka menggunakan laman sesawang tersebut untuk menayangkan iklan dan jenis lain maklumat pemasaran kepada Anda di laman sesawang / Aplikasi kami.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami mungkin mendedahkan dan memindahkan maklumat tersebut kepada pihak ketiga yang memperoleh Unit perniagaan kami, sama ada pengambilalihan itu adalah melalui penggabungan, penyatuan atau pembelian semua atau sebahagian besar aset kami. Anda akan dimaklumkan tentang penjualan semua atau sebahagian besar perniagaan kami kepada pihak ketiga melalui e-mel atau melalui notis penting yang dipaparkan di laman sesawang / Aplikasi.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami mendedahkan maklumat jika dikehendaki secara sah menurut perintah dari entiti kerajaan, pihak berkuasa tempatan, pihak berkuasa berkanun, agensi penguatkuasaan di bawah undang-undang dan pengawalseliaan industri atau pihak berkuasa lain atau dengan niat baik. Kami akan mendedahkan maklumat tersebut untuk:</span>
        <ul style="margin-bottom:0cm;" type="circle">
            <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>mematuhi kehendak undang-undang atau mematuhi proses perundangan;</span></li>
            <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>melindungi hak atau harta kami atau syarikat sekutu kami;</span></li>
            <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>mencegah jenayah atau melindungi keselamatan negara; atau</span></li>
            <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>melindungi keselamatan peribadi pengguna atau orang awam.</span></li>
        </ul>
    </li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Sekiranya berlaku sebarang kecemasan perubatan, jika ada orang yang berhasrat untuk membunuh diri atau berada dalam keadaan perubatan kecemasan, syarikat kami berhak untuk mendedahkan identiti pesakit kepada sumber yang berkaitan.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Pekerja ePink Health , juruaudit, perunding, akauntan, peguam, ejen hartanah, vendor, rakan kongsi pemasaran bersama, syarikat insurans, pengurus hartanah dan pengurus pengurusan dan penasihat profesional.</span></li>
    <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Jika anda melanggan perkhidmatan ePink Health &nbsp;melalui majikan anda secara langsung atau tidak langsung melalui penyedia Penanggung Insurans atau Pentadbir Pihak Ketiga (TPA), kami wajib untuk berkongsi maklumat perubatan anda dengan Penanggung Insurans, TPA dan / atau majikan anda untuk tujuan pengeluaran bil dan tuntutan. HAL INI TIDAK MERANGKUMI INDIVIDU YANG MEMBAYAR SENDIRI DENGAN e-pink.health</span></li>
</ul>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PAUTAN LUAR DI APLIKASI / LAMAN SESAWANG</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Laman sesawang / Aplikasi kami mungkin mempunyai &lsquo;hyperlink&rsquo; iklan ke laman sesawang, aplikasi, kandungan atau sumber lain. Kami tidak mempunyai kawalan ke atas pautan luar seperti yang terdapat dalam Aplikasi / laman sesawang, yang disediakan oleh individu atau syarikat selain Kami. Anda mengakui dan bersetuju bahawa Kami tidak bertanggungjawab atas apa-apa pengumpulan atau pendedahan Maklumat Peribadi Anda oleh mana-mana laman sesawang, aplikasi, syarikat atau individu luar, dan kami juga tidak mengesahkan mana-mana pengiklanan, produk atau bahan lain pada atau tersedia dari aplikasi luaran, laman sesawang atau sumber lain.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Anda juga mengakui dan bersetuju bahawa Kami tidak bertanggungjawab terhadap apa-apa kerugian atau kerosakan yang mungkin ditanggung oleh Anda akibat pengumpulan dan / atau pendedahan maklumat peribadi Anda melalui aplikasi luar, laman sesawang atau sumber, atau sebagai hasil dari apa-apa kebergantungan yang diletakkan oleh Anda pada kelengkapan, ketepatan atau kewujudan sebarang pengiklanan, produk atau bahan lain pada, atau tersedia dari aplikasi, laman sesawang atau sumber lain. Anda mungkin tertakluk dengan dasar privasi Aplikasi luar, laman sesawang dan penyedia sumber mereka sendiri yang mengawal pengumpulan, penyimpanan, pengekalan dan pendedahan Maklumat Peribadi. Kami mengesyorkan bahawa Anda memasuki aplikasi luar atau laman sesawang dan menyemak dasar privasi mereka. Kami membenarkan pihak ketiga / individu untuk memaparkan iklan apabila anda menggunakan laman sesawang / Aplikasi.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>LANGKAH KESELAMATAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Laman sesawang / Aplikasi kami mempunyai langkah-langkah keselamatan yang ketat untuk melindungi kerugian, penyalahgunaan dan pengubahan maklumat di bawah kawalan Kami. Apabila Anda menukar atau mengakses adalah dalam Pemilikan kami, Kami mematuhi garis panduan keselamatan yang ketat, melindunginya daripada akses yang tidak dibenarkan.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Acara &lsquo;Force Majeure&rsquo; bermaksud sebarang peristiwa yang berada di luar kawalan munasabah dan termasuk, tanpa batasan, sabotaj, kebakaran, banjir, letupan, perbuatan Tuhan, kekecohan awam, mogok atau tindakan industri apa pun, rusuhan, pemberontakan, peperangan, tindakan pemerintah, penggodaman komputer, akses tanpa kebenaran kepada data komputer dan peranti penyimpanan, kemalangan komputer, pelanggaran keselamatan dan penyulitan, dan sebagainya.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PILIH / TARIK DIRI</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami menyediakan semua Pengguna dengan peluang untuk menarik diri daripada menerima informasi yang tidak penting (promosi, pemasaran yang berkaitan) daripada kami bagi pihak Rakan kami, dan daripada kami secara umum, selepas menubuhkan akaun.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>KERAHSIAAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami tidak mengumpul data atau maklumat peribadi sensitif Pengguna seperti kata laluan akaun e-mel anda, kata laluan akaun anda di laman sesawang / Aplikasi, maklumat biometrik seperti cap jari, pola suara &amp; wajah dan DNA apa-apa maklumat sensitif yang lain yang sulit atau sensitif oleh sifatnya, tanpa persetujuan anda yang jelas atau melainkan jika perlu oleh undang-undang. Maklumat kewangan seperti butiran Akaun Bank atau Kad Kredit atau Kad Debit atau butiran lain yang berkaitan dengan pembayaran dikumpulkan di laman pembayaran oleh fasilitator pembayaran.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>KEMASKINI DAN MEMADAMKAN MAKLUMAT / AKAUN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Anda mungkin mempunyai akses untuk, mengkaji, membetulkan, mengemas kini, menukar atau memadamkan maklumat profil akaun anda pada bila-bila masa. Hanya log masuk ke akaun anda, pergi ke profil anda, dan buat perubahan yang diperlukan.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Sebelum menyediakan salinan maklumat peribadi anda atau membetulkan, mengemaskini atau memadam maklumat tersebut, kami berhak untuk mengesahkan identiti anda dan maklumat peribadi yang anda minta untuk diakses. Akses kepada atau pembetulan, pengemaskinian atau pemadaman maklumat peribadi anda boleh dinafikan atau dihadkan oleh Kami jika ia melanggar hak orang lain dan / atau dibenarkan oleh undang-undang.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PERUBAHAN KEPADA POLISI PRIVASI INI</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Kami berhak untuk mengemaskini, menukar atau mengubahsuai Polisi ini pada bila-bila masa. Polisi ini akan berkuatkuasa dari tarikh kemas kini, perubahan atau pengubahsuaian tersebut berlaku. Jika Anda terus menggunakan Akaun Anda dan / atau mengakses laman sesawang / Aplikasi walaupun selepas apa-apa perubahan telah dibuat, itu akan dianggap sebagai persetujuan tersirat kepada dasar yang telah diubah.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>COOKIES DAN TEKNOLOGI PENJEJAK LAIN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Laman sesawang / Aplikasi kami dan beberapa laman sesawang kami menggunakan &apos;cookies&apos; dan teknologi penjejak yang lain. &apos;Cookies&apos; adalah fail teks kecil yang boleh digunakan, sebagai contoh, untuk mengumpul maklumat mengenai aktiviti di Laman. Sesetengah cookies dan teknologi lain dapat digunakan untuk mengingatkan semula Maklumat Peribadi yang sebelum ini dimasukkan oleh pengguna laman sesawang. Kebanyakan pelayar membenarkan Anda mengawal cookies, termasuk sama ada untuk menerima atau tidak dan cara untuk memadamkannya.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Anda boleh menetapkan kebanyakan pelayar untuk memaklumkan kepada Anda jika Anda menerima cookie, atau Anda boleh memilih untuk menyekat cookies dengan pelayar Anda, tetapi harap maklum bahawa jika Anda memilih untuk memadam atau menyekat cookie Anda, Anda perlu memasukkan semula ID pengguna asal Anda dan kata laluan untuk mendapatkan akses ke bahagian tertentu laman sesawang / Aplikasi.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Teknologi penjejakan boleh merakam maklumat seperti domain Internet dan nama host; Alamat protokol Internet (IP); perisian pelayar dan jenis sistem pengendalian; corak aliran; dan tarikh dan masa Aplikasi kami diakses. Penggunaan cookies dan teknologi penjejak yang lain membolehkan Kami memperbaiki laman sesawang / Aplikasi kami dan pengalaman anda. Kami juga boleh menganalisa maklumat yang tidak mengandungi Maklumat Peribadi untuk trend dan statistik.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>PEMINDAHAN DATA DAN PERKONGSIAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Di mana ePink Health &nbsp;menganggap perlu atau sesuai untuk tujuan penyimpanan data atau pemprosesan atau menyediakan sebarang perkhidmatan atau produk bagi pihak kami kepada anda, ePink Health &nbsp;boleh memindahkan Maklumat Peribadi kepada kumpulan Syarikat ePink Health &nbsp;atau mana-mana perkhidmatan pihak ketiga atau pembekal produk di dalam atau di luar negara di mana kumpulan syarikat ePink Health &nbsp;ditubuhkan di bawah keadaan yang sama, kerahsiaan dan tahap perlindungan keselamatan.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>TANGGUNG RUGI</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Anda bersetuju dan berjanji untuk menanggung rugi Kami terhadap sebarang tuntutan atau pertikaian oleh mana-mana Pihak Ketiga yang timbul daripada pendedahan Maklumat Peribadi oleh Anda kepada Pihak Ketiga sama ada melalui laman sesawang / Aplikasi kami atau sebaliknya dan apabila Anda menggunakan dan mengakses laman sesawang, aplikasi dan sumber Pihak Ketiga . Kami tidak mempunyai sebarang liabiliti untuk tindakan Pihak Ketiga berkaitan dengan Maklumat Peribadi Anda, yang mungkin telah anda dedahkan kepada Pihak Ketiga tersebut.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>KETERASINGAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Setiap perenggan Dasar Privasi ini adalah berasingan, bebas dan boleh dipisahkan dari semua dan mana-mana perenggan lain di sini kecuali jika dinyatakan secara nyata atau ditunjukkan oleh konteks perjanjian.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Keputusan atau pengisytiharan bahawa satu atau lebih perenggan adalah batal dan tidak sah tidak akan memberi kesan kepada perenggan lain dalam dasar privasi ini.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>MAKLUMAT PERHUBUNGAN</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Sebarang maklum balas atau komen mengenai Dasar Privasi ini cukup dialu-alukan dan boleh dihantar kepada</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>&nbsp;hello@epink.health Kami akan menggunakan semua usaha yang berpatutan secara komersil untuk menangani perkara yang sama.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><strong><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>KONFLIK</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:6.0pt;background:white;'><span style='font-family:"Calibri Light",sans-serif;color:#333333;background:white;'>Sekiranya terdapat ketidakselarasan antara Notis versi Bahasa Inggeris dan versi Bahasa Malaysia, versi Bahasa Inggeris akan digunapakai.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:13px;font-family:"Calibri",sans-serif;margin:0cm;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;'>&nbsp;</span></p>

</div>